{% set version = "1.1-9.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-suppdists
  version: {{ version|replace("-", "_") }}

source:
  fn: SuppDists_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/SuppDists_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SuppDists/SuppDists_{{ version }}.tar.gz
  sha256: 53f53002f7da34015b5466b3dd0a1cdfb49a0576a80401af1d66bc5049ba4606

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('SuppDists')"           # [not win]
    - "\"%R%\" -e \"library('SuppDists')\""  # [win]

about:
  home: no longer valid
  license: GPL (>= 2)
  summary: Ten distributions supplementing those built into R. Inverse Gauss, Kruskal-Wallis,
    Kendall's Tau, Friedman's chi squared, Spearman's rho, maximum F ratio, the Pearson
    product moment correlation coefficient, Johnson distributions, normal scores and
    generalized hypergeometric distributions. In addition two random number generators
    of George Marsaglia are included.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - qwhelan
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
