appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ZY9vgYwRyQPf+XaKPkAt/d33yk1TZnmE5QwVFuMnzXjPldejXW/eyAYrUjzbGtf5aIzd6435a2tRgLby2f6vc+tcAp9T90emlGDW+kMa0muuZKiYmew6HJKAn+j49rkAUtxGrxCOZCcH7fiDdazaZzfJxMbQGlNWnugadE15Frw0k2OinsqDTTUo8mtRovEf0wi1NRvYHNlQb3aOIfTomnNoZaI+t3mNXjHuuL+xgLPwrBYfgkxdviiX1f2B00tsZFdOBl5BGu34YOTQEeBz3E3pE72dQZJU2pw+1GULLqe0zl8nh3HVbuO681jdBHdZ7KzNGZfhAr550Pi4lQI3jp/HDCReUmFvENEN/pHG/P7v6NtBCbY0jjedMAX1Ps0UASKuKtVa6EB+1q77lgC5PKhfHXKbAMvxWsV5lfhR3rj9hxRBytSaIqQhur6fyiMOpUa3w4WNDyaiz5WBpuIHSmZ2KKitDO5E8ItrzAUJiIh3D3foZwkbn0YPRGaNPKM6yDIWHbHBX65xtVDyb8Me7KUsfB5D7VKXcIy3UJkO11o1QFjCTyxi4sJL0w+G2KktXrvxpfp9YBiUTNuj/cEhvJa7zt/rif2bKxLqJkGzSVgfCeHV1mOXrUti9uYwGMbXdXycvc/fmtuX4RJ+CX3h8VEOKmh4JCGtAWtKUCOxyDI=}
bot:
  automerge: true
